config/routes.rb
Aehalo::Application.routes.draw do
  resources :tasks


  resources :groups do
	  resources :members
	end

  resources :cities do
  	resources :reviewers
	  resources :seals
	end

  resources :coordinates

	resources :github

  resources :projects do
    resources :blueprints do
			collection { post :sort }
		end
    resources :notes do
			collection { post :sort }
		end
    resources :participants
	  resources :tasks
  end



  mount StripeEvent::Engine => '/stripe'
	get 'notes/:tag', to: 'notes#index', as: :note
	get 'blueprints/:tag', to: 'blueprints#index', as: :blueprint
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  authenticated :user do
    root :to => 'users#show'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
end

app/models/blueprint.rb
class Blueprint < ActiveRecord::Base
  attr_accessible :id, :project_id, :bpu, :title, :tag_list, :author
  belongs_to :project
  has_many :coordinates
  has_many :notes, :through => :coordinates
	mount_uploader :bpu, BpuUploader

	acts_as_taggable
end

app/controllers/blueprints_controller.rb
class BlueprintsController < ApplicationController
  before_filter :get_project
  
  load_and_authorize_resource


  def get_project
    @project = Project.find(params[:project_id])
  end
  # GET /blueprints
  # GET /blueprints.json
  def index
		if params[:tag]    
			@blueprints = @project.blueprints.tagged_with(params[:tag])
		else
    @blueprints = @project.blueprints
		end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blueprints }
    end
  end

  # GET /blueprints/1
  # GET /blueprints/1.json
  def show
    @blueprint = @project.blueprints.find(params[:id])
		
		@notes = @blueprint.notes.order("position")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blueprint }
    end
  end

  # GET /blueprints/new
  # GET /blueprints/new.json
  def new
    @blueprint = Blueprint.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blueprint }
    end
  end

  # GET /blueprints/1/edit
  def edit
    @blueprint = Blueprint.find(params[:id])
  end

  # POST /blueprints
  # POST /blueprints.json
  def create
    @blueprint = @project.blueprints.new(params[:blueprint])

    respond_to do |format|
      if @blueprint.save
        format.html { redirect_to [@project], notice: 'Blueprint was successfully created.' }
        format.json { render json: [@project, @blueprint], status: :created,
				 location: [@project, @blueprint] }
      else
        format.html { render action: "new" }
        format.json { render json: @blueprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blueprints/1
  # PUT /blueprints/1.json
  def update
    @blueprint = Blueprint.find(params[:id])

    respond_to do |format|
      if @blueprint.update_attributes(params[:blueprint])
        format.html { redirect_to [@project, @blueprint], notice: 'Blueprint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blueprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blueprints/1
  # DELETE /blueprints/1.json
  def destroy
    @blueprint = @project.blueprints.find(params[:id])
    @blueprint.destroy

    respond_to do |format|
      format.html { redirect_to project_blueprints_url }
      format.json { head :no_content }
    end
  end

	def sort
		params[:blueprint].each_with_index do |id, index|
			@project.blueprints.update_all({position: index+1}, {id: id})
		end
		render nothing: true
	end
end

app/helpers/blueprints_helper.rb
module BlueprintsHelper
end

app/views/blueprints/_discussion-form.html.erb
<%= form_for [@project, @blueprint] do |f| %>

	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
		<br>
		<%= f.hidden_field :author, value: current_user.name %>
	</p>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/blueprints/_display.html.erb
<% if File.extname(@blueprint.bpu.to_s) == '.pdf' %>
	<%= link_to 'Open PDF', @blueprint.bpu.to_s, class: 'btn btn-success' %>
<% else %>
	<a href="<%= @blueprint.bpu %>"><%= image_tag @blueprint.bpu %></a>
<% end %>

app/views/blueprints/_form.html.erb
<%= form_for [@project, @blueprint] do |f| %>

	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
		<br>
		<%= f.hidden_field :author, value: current_user.name %>
		<% unless params[:type] == 'discussion' %>
    	<%= f.file_field :bpu %>
		<% end %>
	</p>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/blueprints/_index-sidebar.html.erb
<h4>Project Blueprint Record</h4>
<ul>
	<li>View all blueprints uploaded to a project.</li>
	<li>Open blueprint.</li>
	<li>Can function as the main review structure for city users.</li>
</ul>

<%= link_to 'Back to Project', project_path(@project), :class => 'btn' %>

app/views/blueprints/_show-sidebar.html.erb
<h3><%= best_in_place @blueprint, :title %></h3>
<%= link_to 'Update', edit_project_blueprint_path(@project, @blueprint), :class => 'btn btn-primary' %>
<p>
	<br>
	<b>Belongs to project:</b>
	<%= @blueprint.project_id %>
	<br>
	<b>Created:</b>
	<%= @blueprint.created_at %>
	<br>
	<h4>Blueprint Page</h4>
	<ul>
		<li>View all information related to a blueprint.</li>
		<li><strong>Edit title or add tag.</strong></li>
		<li>Add Notes.</li>
	</ul>
</p>

<strong>Notes:</strong><%= link_to 'Add Note', new_project_note_path(@project, :blueprint_id => @blueprint.id), :class => 'btn' %>
<ul id="notes" data-update-url="<%= sort_project_notes_url %>">
	<% @notes.each do |note| %>
		<%= content_tag_for :li, note do %>
			<span class="handle">[sort]</span>
			<strong><%= best_in_place [@project, note], :note %></strong> <br>
			<%= best_in_place [@project, note], :note_text %>
		<% end %>
	<% end %> 
</ul>

<%= link_to 'Back to Project', project_path(@project), :class => 'btn' %>

app/views/blueprints/edit.html.erb
<h1>Editing blueprint</h1>

<%= render 'form' %>

<%= link_to 'Show', [@project, @blueprint], :class => 'btn btn-mini' %> |
<%= link_to 'Back', project_blueprints_path, :class => 'btn btn-mini' %>

app/views/blueprints/index.html.erb
<div class="row-fluid">
	<div class="span8">
		<h1>Blueprints tagged <i><%= params[:tag] %></i></h1>


		<% @blueprints.each do |blueprint| %>
			<table class="table table-hover">
				<tr>
					<th><strong><%= blueprint.title %></strong><%= link_to 'Show', [@project, blueprint], :class => 'btn btn-mini' %><%= link_to 'Edit', edit_project_blueprint_path(@project, blueprint), :class => 'btn btn-mini' %></th>
				</tr>
			</table>
		<% end %>



	</div>
	<div class="span4">
		<%= render 'index-sidebar' %>
	</div>
</div>

app/views/blueprints/new.html.erb
<% if params[:type] == 'discussion' %>
	<h1>New Discussion</h1>
<% else %>
	<h1>New Blueprint</h1>
<% end %>
<%= render 'form' %>

<%= link_to 'Back', project_path(@project), class: 'btn btn-small' %>

app/views/blueprints/show.html.erb
<div class="row-fluid">
	<div class="span4">
		<%= render 'show-sidebar' %>
	</div>
	<div class="span8">
		<table class="table table-hover table-bordered">
			<tbody>
				<tr>
					<td>
						<%= render 'display' %>
					</td>
				</tr>
			</tbody>
		</table>




	</div>
</div>