config/routes.rb
Aehalo::Application.routes.draw do
  resources :tasks


  resources :groups do
	  resources :members
	end

  resources :cities do
  	resources :reviewers
	  resources :seals
	end

  resources :coordinates

	resources :github

  resources :projects do
    resources :blueprints do
			collection { post :sort }
		end
    resources :notes do
			collection { post :sort }
		end
    resources :participants
	  resources :tasks
  end



  mount StripeEvent::Engine => '/stripe'
	get 'notes/:tag', to: 'notes#index', as: :note
	get 'blueprints/:tag', to: 'blueprints#index', as: :blueprint
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  authenticated :user do
    root :to => 'users#show'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :members_attributes
	has_many :members
	has_many :users, :through => :members, uniq: true
  accepts_nested_attributes_for :members
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
		@member = Member.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new
		user = @group.members.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <%= f.fields_for :members do |builder| %>
    <div class="form-inputs">
      <%= builder.hidden_field :user_id, :value => current_user.id %>
    </div>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/_sidebar_index.html.erb
<h3>Group Index</h3>
<ul>
	<li>The index can display links to all of the groups.</li>
	<li>Authorized users may Create a Group.</li>
	<!--<li></li>
	<li></li>
	<li></li>-->

</ul>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group, class: 'btn btn-small' %> |

app/views/groups/index.html.erb
<div class="row-fluid">
	<div class="span8">
		<% unless current_user.nil? %>
			<% if current_user.has_role? :gold %>
				<br>
				<div class="well">
					<%= link_to 'New Group', new_group_path, :class => 'btn btn-block' %>
				</div>
				<ul>
					<% current_user.groups.each do |g| %>
						<li><%= link_to g.name, group_path(g.id) %></li>
					<% end %>
				</ul>			
			<% else %>
				<p>Users with a group plan may create a group.</p>
			<% end %>
		<% end %>
	</div>
	<div class="span4">
		<%= render 'sidebar_index' %>
	</div>
</div>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(current_user.id), class: 'btn btn-small' %>

app/views/groups/show.html.erb
<div class="row-fluid">
	<div class="span8">
		<p id="notice"><%= notice %></p>

		<p>
			<b>Name:</b>
			<%= @group.name %><%= link_to 'Edit', edit_group_path(@group), :class => 'btn btn-mini' %>
		</p>
		
		<table class="table table-bordered">
			<thead>
				<tr>
					<td>
						<strong>Group Members</strong><a href="#newMember" role="button" class="btn" data-toggle="modal">Add Member</a>
					</td>
				</tr>
			</thead>
			<tbody>
				<% @group.users.each do |user| %>
					<tr>
						<td><%= link_to user.name, user_path(user.id) %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>


	<div class="span4">
		<h3>Groups</h3>
		<ul>
			<li>Primarilly organize users for functional purposes.</li>
			<li><strong>Firms</strong> can use groups to easily associate employees with projects.</li>
			<li>Groups are agile and can be used however end user finds most useful.</li>
		</ul>
	</div>
</div>

<!-- Note Modal -->
<div id="newMember" class="modal hide fade alert alert-info well" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="background-color:#cccccc;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Add Member</h3>
	</div>
	<div class="modal-body" style="max-height:450px;">
		<%= render 'members/form' %>
	</div>
</div>