config/routes.rb
Aehalo::Application.routes.draw do
  resources :tasks


  resources :groups do
	  resources :members
	end

  resources :cities do
  	resources :reviewers
	  resources :seals
	end

  resources :coordinates

	resources :github

  resources :projects do
    resources :blueprints do
			collection { post :sort }
		end
    resources :notes do
			collection { post :sort }
		end
    resources :participants
	  resources :tasks
  end



  mount StripeEvent::Engine => '/stripe'
	get 'notes/:tag', to: 'notes#index', as: :note
	get 'blueprints/:tag', to: 'blueprints#index', as: :blueprint
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  authenticated :user do
    root :to => 'users#show'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :stripe_token, :coupon
  attr_accessor :stripe_token, :coupon
  before_save :update_stripe
  before_destroy :cancel_subscription

  has_many :participants
  has_many :projects, :through => :participants, uniq: true
	has_many :reviewers
	has_many :cities, :through => :reviewers
	has_many :seals, :through => :cities

	has_many :members
	has_many :groups, :through => :members, uniq: true

  # This only allows users participating in a project to view an entire project (Upgrade for Sec.)
  def is_participant?(project_id)
    self.participants.exists?(:project_id => project_id)
  end

	def is_reviewer_of_project?(project_id)
		self.seals.exists?(:project_id => project_id)
	end

	def is_reviewer_of_city?(city_id)
		self.reviewers.exists?(:city_id => city_id)
	end

  def update_plan(role)
    self.role_ids = []
    self.add_role(role.name)
    unless customer_id.nil?
      customer = Stripe::Customer.retrieve(customer_id)
      customer.update_subscription(:plan => role.name)
    end
    true
  rescue Stripe::StripeError => e
    logger.error "Stripe Error: " + e.message
    errors.add :base, "Unable to update your subscription. #{e.message}."
    false
  end
  
  def update_stripe
    return if email.include?(ENV['ADMIN_EMAIL'])
    return if email.include?('@example.com') and not Rails.env.production?
    if customer_id.nil?
      if !stripe_token.present?
        raise "Stripe token not present. Can't create account."
      end
      if coupon.blank?
        customer = Stripe::Customer.create(
          :email => email,
          :description => name,
          :card => stripe_token,
          :plan => roles.first.name
        )
      else
        customer = Stripe::Customer.create(
          :email => email,
          :description => name,
          :card => stripe_token,
          :plan => roles.first.name,
          :coupon => coupon
        )
      end
    else
      customer = Stripe::Customer.retrieve(customer_id)
      if stripe_token.present?
        customer.card = stripe_token
      end
      customer.email = email
      customer.description = name
      customer.save
    end
    self.last_4_digits = customer.active_card.last4
    self.customer_id = customer.id
    self.stripe_token = nil
  rescue Stripe::StripeError => e
    logger.error "Stripe Error: " + e.message
    errors.add :base, "#{e.message}."
    self.stripe_token = nil
    false
  end
  
  def cancel_subscription
    unless customer_id.nil?
      customer = Stripe::Customer.retrieve(customer_id)
      unless customer.nil? or customer.respond_to?('deleted')
        if customer.subscription.status == 'active'
          customer.cancel_subscription
        end
      end
    end
  rescue Stripe::StripeError => e
    logger.error "Stripe Error: " + e.message
    errors.add :base, "Unable to cancel your subscription. #{e.message}."
    false
  end
  
  def expire
    UserMailer.expire_email(self).deliver
    destroy
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  load_and_authorize_resource

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
		if params[:id].nil?
    	@user = User.find(current_user.id)
		else
			@user = User.find(params[:id])
		end
		@project = Project.new
		user = @project.participants.build
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    role = Role.find(params[:user][:role_ids]) unless params[:user][:role_ids].nil?
    params[:user] = params[:user].except(:role_ids)
    if @user.update_attributes(params[:user])
      @user.update_plan(role) unless role.nil?
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/views/users/_sidebar.html.erb
<div class="well">
	<h3><%= @user.name %></h3>
	<% if current_user.id == @user.id %>
		<a href="#viewUser" role="button" class="btn btn-primary btn-block" data-toggle="modal">Account Details</a>
	<% end %>
</div>
<div class="well">
	<h3>User Page</h3>
	<ul>
		<li>Displays the projects the current user is participating in.</li>
		<li>A user is granted access only to his/her 'User Page.'</li>
		<li><strong>New Project</strong> capability.</li>
	</ul>
</div>
<div class="well">
	<h3>My Groups:</h3>
	<% current_user.groups.each do |g| %>
		<li><%= link_to g.name, group_path(g.id) %></li>
	<% end %>
</div>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline' %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
	  <thead>
      <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Registered</th>
          <th>Role</th>
          <th></th>
          <th></th>                                      
      </tr>
  </thead>   
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.to_date %></td>
        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
        <td>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
          <%= render user %>
        </td>
        <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>                                       
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<div class="row-fluid">
	<div class="span8">
		<% if current_user.id == @user.id %>
			<% @user.cities.each do |c| %>
				<div class="alert alert-info">
					<h1>Designated Reviewer at: <%= link_to c.name, city_path(c) %></h1>
					<p><span class="lead">Click your city to see more options.</span></p>
				</div>
			<% end %>
			<table class="table table-bordered">
				  <tr>
				    <td><h1>My Halo<a href="#newProject" role="button" class="btn btn-primary pull-right" data-toggle="modal">Create Project</a></h1></td>
				  </tr>
					<tr>
						<td>
							<ul>
								<% @user.projects.each do |p| %>
									<li><%= link_to p.name, project_path(p), class: 'lead' %></li>
								<% end %>						
						</td>			  
					</tr>
			</table>
		<% else %>
			(Work in progress.) Request this user to join your group.
		<% end %>
	</div>

<!-- In sidebar partial -->
  <div class="span4">
	  <%= render "sidebar" %>
  </div>
</div>
<% if current_user.id == @user.id %>
	<!-- New Project Modal -->
	<div id="newProject" class="modal hide fade alert alert-info well" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="background-color:#cccccc;">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3 id="myModalLabel">Create Project</h3>
		</div>
		<div class="modal-body" style="max-height:450px;">
			<div ng-controller="ProjectCtrl">
			<form ng-submit="addProject()">
					<input type="text" ng-model="newProject.name">Project Name<br>
					<input type="number" ng-model="newProject.manager_id" ng-init="value='<%= @user.id %>'" value="{{value}}" style="display:none;">Project Manager(Hidden)<br>
					<input type="number" ng-model="newProject.city_id">City<br>
					<input type="submit" value="Add {{newProject.name}}" class="btn btn-primary">
				</form>
			</div>
		</div>
	</div>

	<!-- View Account Modal -->
	<div id="viewUser" class="modal hide fade alert alert-info" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="background-color:#cccccc;">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3 id="myModalLabel"><%= @user.name %></h3>
		</div>
		<div class="modal-body" style="max-height:450px;">
			<p>
				<span class="userInfo">
					ID: <strong><%= @user.id %></strong><br>
					Name: <strong><%= @user.name %></strong><br>
					Email: <strong><%= @user.email %></strong><br><br>
					<%= link_to 'Edit Account', edit_user_registration_path, class: 'btn btn-success' %>
				</span>
			</p>
		</div>
	</div>
<% end %>