config/routes.rb
Aehalo::Application.routes.draw do
  resources :tasks


  resources :groups do
	  resources :members
	end

  resources :cities do
  	resources :reviewers
	  resources :seals
	end

  resources :coordinates

	resources :github

  resources :projects do
    resources :blueprints do
			collection { post :sort }
		end
    resources :notes do
			collection { post :sort }
		end
    resources :participants
	  resources :tasks
  end



  mount StripeEvent::Engine => '/stripe'
	get 'notes/:tag', to: 'notes#index', as: :note
	get 'blueprints/:tag', to: 'blueprints#index', as: :blueprint
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  authenticated :user do
    root :to => 'users#show'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :id, :name, :participants_attributes, :sealed, :blueprints_attributes, :city_id
  
	# Products of a project
  has_many :blueprints
  has_many :notes
	has_many :participants, :dependent => :destroy
  has_many :users, :through => :participants, :uniq => true
  accepts_nested_attributes_for :participants
  accepts_nested_attributes_for :blueprints
  accepts_nested_attributes_for :notes

	# For Sign Seal Submit to cities
	has_one :seal, :dependent => :destroy
	has_one :city, :through => :seal
	
	# For Todo Lists
	has_many :tasks

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	skip_before_filter :verify_authenticity_token, :only => [:create] #Temp fix so AngularJS updates model
  load_and_authorize_resource
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
		@blueprints = @project.blueprints.order("position")
		@blueprint = Blueprint.new
		@participant = Participant.new
		@note = Note.new
		@user = @project.users.each
		blueprint = @note.coordinates.build
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
      format.pdf do
		    pdf = ProjectPdf.new(@project)
		    send_data pdf.render, filename: "project_#{@project.name}.pdf"
		  end
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    user = @project.participants.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_blueprint-table.html.erb
<p><span class="lead">Click-to-edit is enabled on all notes and tags.</span><br><span class=""><i>Use commas to seperate tags. Components outlined in red are draggable.</i></span></p>
<% @blueprints.each do |blueprint| %>
	<script>
		jQuery(function() {});

		$('#blueprint_<%= blueprint.id %>').click(function() {
			return $('#blueprint-table-<%= blueprint.id %>').toggle();
		});
	</script>
	<div id="blueprint-table-<%= blueprint.id %>" class="well well-small" style="display: none;" draggable>
		<table class="table table-bordered">
			<tr class="table-row">
				<td>
					<div class="pull-right">
						<i><span class="muted"><%= blueprint.author %></span></i>
						<% if blueprint.bpu? %>
							<strong> Blueprint</strong>
							<%= link_to 'Overview', project_blueprint_path(@project, blueprint.id), class: 'btn' %>
							<a href="#myModal-<%= blueprint.id %>" role="button" class="btn" data-toggle="modal">Preview</a>
						<% else %>
							<strong> Discussion</strong>
						<% end %>
					</div>
					<h3><%= link_to blueprint.title, [@project, blueprint] %></h3>
					<i><%= best_in_place [@project, blueprint], :tag_list, nil: 'Click to add a tag.' %></i></li>
				</td>
			</tr>
			<tr class="table-row">
				<th>Notes <a href="#newNote" role="button" class="btn btn-small" data-toggle="modal">Add Note</a></th>
			</tr>
			<tr class="table-row">
				<td>
					<% blueprint.notes.each do |note| %>
						<ul id="note-table-<%= note.id %>" class="unstyled">
							<li><strong><%= best_in_place [@project, note], :note, nil: 'Click to add a note title.' %>
								<% if note.user_id? %>
									<%= link_to 'Author', user_path(note.user_id) %>	
								<% end %>
							</strong> 
							</li>
							<li><%= best_in_place [@project, note], :note_text, nil: 'Click to add note text.' %></li>
						</ul>
					<% end %>
				</td>
			</tr>
		</table>
		<% if blueprint.bpu? %>
			<!-- Hidden Modal -->
			<div id="myModal-<%= blueprint.id %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h3 id="myModalLabel"><%= blueprint.title %></h3>
				</div>
				<div class="modal-body">
					<% if File.extname(blueprint.bpu.to_s) == '.pdf' %>
						<%= link_to 'Open PDF', blueprint.bpu.to_s, class: 'btn btn-success' %>
					<% else %>
						<a href="<%= blueprint.bpu %>"><%= image_tag blueprint.bpu %></a>
					<% end %>
				</div>
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
				</div>
			</div>
			<!-- End Hidden Modal -->
		<% end %>
	</div>
<% end %>

app/views/projects/_content-nav.html.erb
<!-- Drag Order is affected by drag components in angular" -->
<div id="contents" class="well well-small" draggable>
	<h3>Contents</h4>
	<p><span class=""><i>Click to display contents. Drag to change the display order.</i></span></p>
	<ol id="project-content-nav" data-update-url="<%= sort_project_blueprints_url(@project) %>">
		<% @blueprints.each do |b| %>
			<%= content_tag_for :li, b do %>
				<%= link_to b.title, '#', class: '' %>
			<% end %>
		<% end %>
	</ol>
</div>
<div id="browseTags" class="well well-small" draggable>
	<h3>Browse Tags</h3>
	<div id="tag_cloud">
		<% tag_cloud Blueprint.tag_counts, %w[s m l] do |b, css_class| %>
			<%= link_to b.name, blueprint_path(b.name, project_id: @project.id), class: css_class %>
		<% end %>
	</div>
</div>

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
	<% if current_user.has_role? :admin %>
		<div class="form-inputs">
		  <%= f.input :sealed %>
		</div>
	<% end %>
  <%= f.fields_for :participants do |builder| %>
    <div class="form-inputs">
      <%= builder.hidden_field :user_id, value: current_user.name %>
    </div>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/_participant-sidebar.html.erb
<div id="projectBox" class="well" draggable>
	<p><h3></h3></p>
	
	<div id="participant-list">
		<br>
		<strong>Participants:</strong>
		
		<ol>
			<% @project.users.each do |user| %>
				<li><%= link_to user.name, user_path(user.id) %></li>
			<% end %>
		</ol>
	</div>
</div>
<div id="info" class="well well-small" draggable>
	<h3>Project Page (PARTICIPANT)</h3>
	<ul>
		<li>This page acts as a hub for all aspects of a project.</li>
		<li>Any user participating in a project is capable of using this page</li>
		<li><strong>Add Drawing</strong> capability. Uploads digital blueprint to project.</li>
		<li><strong>Add Note</strong> capability. Project or blueprint specific.</li>
		<li>Click the note tags to add or edit them. <strong>In-place-editing</strong></li>
	</ul>
	
</div>

app/views/projects/_participant.html.erb
<div class="span3">
	<%= render 'content-nav' %>
</div>
<div class="span6">
	<%= render 'blueprint-table' %>
</div>	
<div class="span3">
		<%= render 'participant-sidebar' %>
</div>

<div id="read-review" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Project Review</h3>
  </div>
  <div class="modal-body">
    <%= render 'review' %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/projects/_review.html.erb
<h4>Sealed: <%= @project.sealed %></h4>
<p>This is what reviewers of the project will see.</p>
<div>
	<ol>
		<% @project.blueprints.each do |blueprint| %>
			<%= content_tag_for :li, blueprint do %>
				<h4><%= link_to 'Open', blueprint.bpu.to_s, class: 'btn btn-primary btn-mini' %> <%= blueprint.title %></h4>
				<p><span class=""> <%= blueprint.tag_list %></span></p>
				<ul class="unstyled">
					<% blueprint.notes.each do |note| %>
						<li><p><strong><%= note.note %></strong></p></li>
						<li><p><%= note.note_text %></p></li>
					<% end %>
				</ul>
			<% end %>
		<% end %>
	</ol>
</div>

app/views/projects/_reviewer-sidebar.html.erb
<h3>Project Page (REVIEWER)</h3>
<ul>
	<li>This view is unique to city users for reviewing the project.</li>
	<li>Only visible after 'sign and seal'</li>
</ul>

<div class="well well-small">
	<h3>Contents</h3>
	<ol>
		<% @blueprints.each do |b| %>
			<%= content_tag_for :li, b do %>
				<a href="#blueprint-table-<%= b.id %>">
					<%= b.title %>
				</a>
			<% end %>
		<% end %>
	</ol>
</div>

app/views/projects/_top-bar.html.erb
<div class="well well-small" draggable>
	<ul class="inline pull-right" style="padding-top:1em;">
		<li>
			<div class="btn-group btn-block">
				<a class="btn btn-primary btn-block dropdown-toggle" data-toggle="dropdown" href="#">
					Contribute to Project
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					<li>
						<a href="#newBlueprint" role="button" class="" data-toggle="modal">Upload Blueprint</a> 
					</li>
					<li>
						<a href="#newDiscussion" role="button" class="" data-toggle="modal">Start Discussion</a>
					</li>
				</ul>
			</div>
		</li>
		<li>
			<a href="#newParticipant" role="button" class="btn btn-primary" data-toggle="modal">Add Participant</a>
		</li>
		<li>
			<%= link_to "Printable Project (PDF)", project_path(@project, format: "pdf"), class: 'btn btn-info' %>
		</li>
		<li>
			<a href="#read-review" role="button" class="btn" data-toggle="modal">Preview</a>
		</li>
		<li class="dropdown">
			<a href="#" class="dropdown-toggle btn btn-inverse" data-toggle="dropdown">
				<span class="">
					Toggle Views
					<b class="caret"></b>
				</span>
			</a>
			<ul class="dropdown-menu unstyled" role="menu" aria-labelledby="dLabel">
					<li>
						<%= link_to @project.name, '#', id: 'hideProjectBox' %>
					</li>
					<li>
						<%= link_to 'Browse Tags', '#', id: 'hideBrowseTags' %>
					</li>
					<li>
						<%= link_to 'Contents', '#', id: 'hideContents' %>
					</li>
					<li>
						<%= link_to 'Information', '#', id: 'hideInfo' %>
					</li>
			</ul>
		</li>
	</ul>
	<h2><%= best_in_place @project, :name %><sub><i class="icon-pencil"></i></sub></h2>
</div>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table class="table table-hover table-bordered">
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.id %></td>
    <td><%= project.name %></td>
    <td><%= link_to 'Show', project, :class => 'btn' %></td>
    <td><%= link_to 'Edit', edit_project_path(project), :class => 'btn' %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path, :class => 'btn' %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="row">
		<%= render "top-bar" %>
		<% unless current_user.has_role? :admin %>
			<% unless @project.sealed == true %>
				<% if current_user.is_reviewer_of_project?(@project.id) or current_user.is_participant?(@project.id) %>
					<%= render 'participant' %>
				<% end %>
			<% else %>
				<% if current_user.is_reviewer_of_project?(@project.id) or current_user.is_participant?(@project.id) %>
					<div class="span8">
						<%= render 'review' %>
					</div>
					<div class="span4">
						<%= render 'reviewer-sidebar' %>
					</div>
				<% end %>
			<% end %>
				
		<% else %>
			<%= render 'participant' %>			
		<% end %>
</div>

<!-- Upload Modal -->
<div id="newBlueprint" class="modal hide fade alert alert-info well" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="background-color:#cccccc;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Upload to A&E Halo</h3>
	</div>
	<div class="modal-body" style="max-height:450px;">
		<%= render 'blueprints/form' %>
	</div>
</div>

<!-- Discussion Modal -->
<div id="newDiscussion" class="modal hide fade alert alert-info well" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="background-color:#cccccc;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Start Discussion</h3>
	</div>
	<div class="modal-body" style="max-height:450px;">
		<%= render 'blueprints/discussion-form' %>
	</div>
</div>

<!-- Participant Modal -->
<div id="newParticipant" class="modal hide fade alert alert-info well" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="background-color:#cccccc;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Add Participant</h3>
	</div>
	<div class="modal-body" style="max-height:450px;">
		<%= render 'participants/form' %>
	</div>
</div>

<!-- Note Modal -->
<div id="newNote" class="modal hide fade alert alert-info well" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="background-color:#cccccc;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Add Note</h3>
	</div>
	<div class="modal-body" style="max-height:450px;">
		<%= render 'notes/form' %>
	</div>
</div>